InitialiseSnakeFlow
include_EdgeInformation
include_GridCheck
include_Mex_Wrapper
include_Optimisation
include_PostProcessing
include_SnakeParam
include_Validation
include_Utilities
include_CheckResultsLight


pltPaths=PreplotUtil({'C:\Users\ap1949\Local Documents\PhD\Development Work\Snakes Volume Parametrisation\results\Optimisation\HPC\TestAeroGradients\Set1'});